config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  resources :players
  resource :user_session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :games, only: [:new, :create]
  resources :teams, only: [:new, :create]

  get 'home' => 'home#index', as: 'home'
  get 'landing/index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :player_games
  has_many :players, through: :player_games

  validates :player_games, :player, presence: true

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :player_games
  has_many :games, through: :player_games
  has_many :player_teams
  has_many :teams, through: :player_teams
  has_many :player_team_games
  has_many :team_games, through: :player_team_games

# NEED SOME WAY TO STRIP CELL PHONE NUMBER IN ORDER TO VALIDATE IT...

  validates :first_name, :last_name, :email, :cell, presence: true
  validates :first_name, :last_name, length: { minimum: 2 }
  validates :cell, format: { :with => /\A(\+1)?[0-9]{10}\z/, :message => "Not a valid 10-digit telephone number" }
  validates :email, format: { with: /.+@.+\..+/, message: "must be an email address" }
  validates :points, :negs, numericality: true

  before_validation :set_defaults,  on: :create

  def fullname
    "#{first_name} #{last_name}"
  end

  private

  def set_defaults
    self.points ||= 0
    self.negs ||= 0
  end

end

app/models/player_game.rb
class PlayerGame < ActiveRecord::Base
  belongs_to :player
  belongs_to :game

  validates :player_id, :game_id, presence: true

end

app/models/player_team_game.rb
class PlayerTeamGame < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :player_teams
  has_many :players, through: :player_teams

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/team_game.rb
class TeamGame < ActiveRecord::Base
  has_many :team_player_games
  has_many :players, through: :team_player_games

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :email, :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :email, format: { with: /.+@.+\..+/, message: "must be an email address" }, uniqueness: true
  validates :name, uniqueness: true
  validates :password, confirmation: true
  validates :password, :password_confirmation, presence: { on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game),  notice: "Your new game was successfully created."
    else
      flash.alert = "Please fix the errors below to continue."
      render :new
    end
  end

  def show
    @game = Game.find_by_id(params[:id])
  end

  def index
    @games = Game.all
  end

  def initialize_game
    if params[:id].present?
      @game = Game.find(params[:id])
    else
      @game = Game.new
    end
    if params[:game].present?
      @game.assign_attributes(game_params)
    end
  end

  def game_params
    params.require(:game).permit(:date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_user, except: [:index, :edit, :update]
  before_action :require_login, except: [:show]

  def check_auth
    unless logged_in?
      redirect_to root_path
    end
  end

  def index
    @user = User.find(session[:user_id]).name
  end

  def action
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :initialize_player

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to player_path(@player)
    else
      flash.alert = "Please fix the errors below to continue."
      render :new
    end
  end

  def update
    if @player.save
      flash.notice = "#{@player.first_name} was updated successfully"
      redirect_to players_path
    else
      flash.alert = "Please fix the errors below to continue."
      render :edit
    end
  end


  def show
    @player = Player.find_by_id(params[:id])
  end


  def index
    @players = Player.all
  end

  def destroy
    @player = Player.find_by_id(params[:id])
    if @player.present?
      @player.destroy
  end
    redirect_to players_path, notice: "#{@player.fullname} has been removed."
  end


    protected

  def initialize_player
    if params[:id].present?
      @player = Player.find(params[:id])
    else
      @player = Player.new
    end
    if params[:player].present?
      @player.assign_attributes(player_params)
    end
  end

  def player_params
    params.require(:player).permit(:first_name, :last_name, :email, :cell)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user][:email], params[:user][:password])
      redirect_to home_path
    else
      @user = User.new(email: params[:user][:email])
      flash.alert = "We could not sign you in.  Please check your email/password and try again."
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to home_path
    else
      flash.alert = "Please fix the errors below to continue."
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/create.html.erb
<h1> Game#create</h1>

app/views/games/new.html.erb
<div class="show_main">
<h3>Here are the available players:</h3>

  <%= simple_form_for @game do |f| %>
  <%= f.collection_check_boxes :player_ids, Player.all, :id, :fullname %>
  <%= f.button :submit, "Save Game" %>
  <% end %>
</div>

app/views/games/show.html.erb
<h1> Game#show</h1>

app/views/games/update.html.erb
<h1> Game#update</h1>

app/views/home/index.html.erb
<div class="home_base">

  <div class="left_home">
    <%= image_tag("HFA.jpg", :alt => "Hume-Fogg Magnet") %>
  </div>

  <div class="wide_home">
    <h1 class="home_blue">What's the plan, <%= @user %>?</h1>

    <div class="wide_home_left">
      <ul>
        <li><%= button_to "Add a new player", new_player_path, :class => "button" "main", :method => :get %></li>
        <li><%= button_to "View players", players_path, :class => "button" "main", :method => :get %></li>
      <ul>
    </div>
    <div class="wide_home_right">
      <ul>
        <li><%= button_to "Create teams", root_path, :class => "button" "main", :method => :get %></li>
        <li><%= button_to "Set up a game", new_game_path, :class => "button" "main", :method => :get %></li>
      <ul>
    </div>

      <ul>
        <li><%= button_to "Start playing", root_path, :class => "button" "top_heavy", :method => :get %></li>
      <ul>

  </div>
</div>

app/views/landing/index.html.erb
<div class="outer">

  <div class="logo">
    <h3>welcome to</h3>
    <h1>QUIZLYTICS</h1>
    <h3>a quizbowl point tracking system</h3>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Quizlytics</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="centered-navigation" role="banner">
      <div class="centered-navigation-wrapper">
      <a href="#" class="mobile-seal">
        <%= image_tag("seal_small.png", :alt => "Hume-Fogg Magnet seal") %>
      </a>
      <a href="#" class="centered-navigation-mobile-menu">MENU</a>
        <nav role="navigation">
          <ul class="centered-navigation-menu">
            <% if !logged_in? %>
              <% unless controller_name.start_with? "user" %>
                <li class="nav-link">
                  <%= link_to "I'm a new nerd!", new_user_path %>
                </li>
              <% end %>

              <li class="nav-link seal">
                <%= image_tag("seal_small.png", :alt => "Hume-Fogg Magnet seal") %>
              </li>

              <% unless controller_name.start_with? "user" %>
                <li class="nav-link">
                  <%= link_to "I'm a returning nerd!", new_user_session_path %>
                </li>
              <% end %>

            <% else %>

              <li class="nav-link">
                <%= link_to "I'm done for today.", user_session_path, method: :delete %>
              <li class="nav-link seal">
                <%= image_tag("seal_small.png", :alt => "Hume-Fogg Magnet seal") %></li>
              <li class="nav-link">
                <%= link_to "See the project code.", "https://github.com/complikatyed/quizlytics" %>
              </li>

            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>
    <%= yield %>
    <p> </p>
    <p> </p>
    <footer class="centered-navigation">
      <div class="centered-navigation-wrapper">
        <ul class="centered-navigation-menu padded">
          <li class="padded">
            <%= link_to '"Hume-Fogg, just a bunch of nerds having a good time."', "http://humefogghs.mnps.org/pages/Hume_Fogg_Magnet_High_School" %>

          </li>
        </ul>
      </div>
    </footer>

  </body>
</html>

app/views/players/_form.html.erb
<%= simple_form_for player do |f| %>
  <%= f.input :first_name, placeholder: "Player's first name", input_html: { class: 'player_input' }%>
  <%= f.input :last_name, placeholder: "Player's last name", input_html: { class: 'player_input' }  %>
  <%= f.input :email, placeholder: "Player's email address", input_html: { class: 'player_input' }  %>
  <%= f.input :cell, placeholder: "Player's cell number - just the ten digits", input_html: { class: 'player_input' } %>
  <% button_text = (player.persisted?) ? "Save Changes" : "Player Ready" %>
  <%= f.button :submit, button_text, class: 'player_input' %>
<% end %>

app/views/players/edit.html.erb
<div class="outer_player">
  <h1>Thanks for keeping your information up to date!</h1>
  <div class="center">

    <h3 class="white">Please make any necessary edits below:</h3>

    <%= render partial: 'players/form', locals: { player: @player } %>
    <%= button_to "Remove This Player", @player, method: :delete, data: { confirm: "Are you sure?" }, class: 'player' %>
  </div>
</div>

app/views/players/index.html.erb
<div class="outer_player1">
  <h1 class="blue">HFA Quiz Bowl Players</h1>
  <h2 class="blue">Click on a player's name to edit or remove that player.</h2>

  <table class="players">
    <tr>
      <th class="wide">Player</th>
      <th class="wider">Email</th>
      <th class="wide">Cell</th>
      <th class="narrow">Points</th>
      <th class="narrow">Negs</th>
    </tr>

  <% @players.each do |player| %>
    <tr>
      <td class="wide"><%= link_to "#{player.first_name} #{player.last_name[0]}", edit_player_path(player) %></td>
      <td class="wider"><%= player.email%></td>
      <td class="wide"><%= player.cell%></td>
      <td class="narrow"><%= player.points%></td>
      <td class="narrow"><%= player.negs%></td>
    </tr>
  <% end %>
  </table>

  <br>
  <ul class="shifted">
    <li class="plain"><%= link_to "Add a new player", new_player_path %></li>
    <li class="plain">&nbsp; | &nbsp;</li>
    <li class="plain"><%= link_to "Return to options page", home_path %></li>
  </ul>
</div>

app/views/players/new.html.erb
<div class="outer_player">
  <h1>Thanks for choosing to join the team!</h1>
  <div class="center">

    <h3 class="white">Please provide the information below:</h3>

    <%= render partial: 'players/form', locals: { player: @player } %>
  </div>
</div>

app/views/players/show.html.erb
<div class="show_main">

  <div class="show_first">
    <h3>Here's your new player:</h3>
    <ul>
      <li><h2><%= "#{@player.first_name} #{@player.last_name[0]}" %></h2></li>
      <li><%= "#{@player.email}" %></li>
      <li><%= "#{@player.cell}" %></li>
      <li><%= "Points: #{@player.points}"%></li>
      <li><%= "Negs: #{@player.negs}"%></li>
    </ul>
  </div>

  <div class="show_second">
    <h1 class="blue">What would you like to do next?</h1>

    <div class="show_second_left">
      <ul>
        <li><%= button_to "Add a new player", new_player_path, :class => "button" "main", :method => :get %></li>
        <li><%= button_to "View players", players_path, :class => "button" "main", :method => :get %></li>
      </ul>
    </div>
    <div class="show_second_right">
      <ul>
        <li><%= button_to "Create teams", root_path, :class => "button" "main" %></li>
        <li><%= button_to "Set up a game", new_game_path, :class => "button" "main", :method => :get %></li>
      </ul>
    </div>
    <ul>
      <li><%= button_to "Start playing", root_path, :class => "button" "main" %></li>
    </ul>

  </div>
</div>

app/views/refills/_centered_navigation.html.erb
<header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
        <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
        <li class="nav-link logo">
          <a href="javascript:void(0)" class="logo">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image">
          </a>
        </li>
        <li class="nav-link"><a href="javascript:void(0)">Testimonials</a></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
            <li class="more"><a href="javascript:void(0)">Item with submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                <li><a href="javascript:void(0)">Another Item</a></li>
              </ul>
            </li>
            <li class="more"><a href="javascript:void(0)">Another submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                <li><a href="javascript:void(0)">An Item</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="nav-link"><a href="javascript:void(0)">Sign up</a></li>
      </ul>
    </nav>
  </div>
</header>

app/views/refills/_type_system_slab.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700' rel='stylesheet' type='text/css'>
</head>

<article class="type-system-slab">
  <p class="type">Article Type</p>
  <h1>Article Heading</h1>
  <h2>These override some of the styles specified in the <code>_variables.scss</code> and <code>_typography.scss</code> partials in <a href="//bitters.bourbon.io">Bitters</a>. You can replace the typography variables and the header font specifications in Bitters with these styles. Then you won&rsquo;t need the wrapping class <code>.type-system-name</code>.</h2>
  <p class="date">30 Mar 2014</p>
  <p><span>Lorem ipsum dolor sit amet</span>, consectetur adipisicing elit. Consequatur a, ullam, voluptatum incidunt neque doloremque vel inventore distinctio laudantium harum</a> illo quam nulla dolor alias iure impedit! Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit.
    <a href="javascript:void(0)" class="read-more">Read More <span>&rsaquo;</span></a>
  </p>
  <h3>Subheading lorem</h3>
  <p><span>Consequatur ullam, voluptatum</span> incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit. Accusamus. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit! Accusamus.</p>
  <hr>
  <p class="author">Author Name</p>
</article>

app/views/user_sessions/new.html.erb
<div class="users_base">
  <h1 class="white"> Welcome Back, Nerd Friend!</h1>
  <h2 class="blue">Please verify your identity below.</h2>

  <div class="left_user_session">
  <%= simple_form_for @user, url: user_session_path do |f| %>
    <%= f.input :email, placeholder: "What's your email address?", input_html: { class: 'user_first' }  %>
    <%= f.input :password, placeholder: "What's your password?", input_html: { class: 'user' }  %>
    <%= f.button :submit, "Let's do this!", class: "user" %>
  <% end %>
  </div>

  <div class="right_user_session">
    <%= image_tag("quizbowl.jpg", :alt => "Keep Calm and Quiz Bowl") %>
  </div>

</div>

app/views/users/new.html.erb
<div class="users_base">
  <h1 class="white"> Welcome New Nerd Friend!</h1>
  <h2 class="blue"> Please sign up below.</h2>

  <div class="left_users"> 

    <%= simple_form_for @user do |f| %>
      <%= f.input :name, placeholder: "Choose a username", input_html: { class: 'user_first' }  %>
      <%= f.input :email, placeholder: "What's your email address?", input_html: { class: 'user' }  %>
      <%= f.input :password, placeholder: "Choose a password", input_html: { class: 'user' }  %>
      <%= f.input :password_confirmation, placeholder: "What was that password again?", input_html: { class: 'user' }  %>
      <%=f.button :submit, "Sign me up, coach!", class: "user" %>

    <% end %>
  </div>

  <div class="right_users">
    <%= image_tag("buzzer.jpg", :alt => "Hand with quiz bowl buzzer") %>
  </div>

</div> 